# Generated by Django 3.1.7 on 2021-03-16 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20210316_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insulin',
            name='dosage',
            field=models.FloatField(),
        ),
    ]
