# Generated by Django 3.1.6 on 2021-04-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_auto_20210316_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glucose',
            name='categories',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.recordingcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='glucose',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
